server:
  port: 8087
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: API
          uri: http://medical-customer-web-service.medical.svc.cluster.local
          predicates:
            - Path=/medical/**
        - id: WEB
          uri: http://medical-customer.medical.svc.cluster.local
          predicates:
            - Path=/**

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: demo-client
            client-secret: dd1zsKouT3UtZHiP6bJ6YCjIVTO1YPrZ
            authorization-grant-type: authorization_code
            redirect-uri: https://medical.pirveli.ge/login/oauth2/code/keycloak
            scope:
              - email
              - profile
              - roles
              - openid
        provider:
          keycloak:
            issuer-uri: https://auth.pirveli.ge/realms/xracoon-demo
            user-name-attribute: preferred_username


      resourceserver:
        jwt:
          issuer-uri: https://auth.pirveli.ge/realms/xracoon-demo
