server:
  port: 8088
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: withSecurity
          uri: http://localhost:8081
          predicates:
            - Path=/api/secured/**
        - id: withOutSecurity
          uri: http://localhost:8083
          predicates:
            - Path=/api/**

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: demo-client
            client-secret: dd1zsKouT3UtZHiP6bJ6YCjIVTO1YPrZ
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8088/login/oauth2/code/keycloak
            scope:
              - email
              - profile
              - roles
        provider:
          keycloak:
            authorization-uri: http://auth.pirveli.ge/realms/xracoon-demo/protocol/openid-connect/auth
            token-uri: http://auth.pirveli.ge/realms/xracoon-demo/protocol/openid-connect/token
            user-info-uri: http://auth.pirveli.ge/realms/xracoon-demo/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username